scrape_configs:
  - job_name: 'spring_micrometer'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'spring-boot-service'
          group: 'demo'