version: '3'
services:
  prometheus-app:
    image: 'prom/prometheus:latest'
    ports:
      - "9090:9090"
    volumes:
      - './prometheus-data:/prometheus-data'
    command:
      - '--config.file=/prometheus-data/prometheus.yml'
